title: "my-blog"
description: "Blog kecil buat dokumentasi catatan pribadi"
author: "Rofi (Fixploit03)"
theme: minima
url: "https://fixploit03.github.io"
baseurl: "/my-blog"
permalink: /:year/:month/:day/:title/
minima:
  social_links:
    github: fixploit03
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
future: true
