title: "my-blog"
description: "Blog kecil buat dokumentasi catatan pribadi"
author: "Rofi (Fixploit03)"

remote_theme: pages-themes/hacker

url: "https://fixploit03.github.io"
baseurl: "/my-blog"
permalink: /:year/:month/:day/:title/

future: true

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
